name: Hosting Static Website

on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
          echo "Starting the build job"
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup nodejs'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn install
      - run: yarn build

      - name: 'Write config'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{ocid1.user.oc1..aaaaaaaa2ylitpt5mc3d5z37vspx4xfkbi4dmcfdiog77v2bbjuvom4od2hq}}" >> ~/.oci/config
          echo "fingerprint=${{0a:7a:c9:bb:9c:26:8e:75:25:d3:69:58:a3:f9:75:a7}}" >> ~/.oci/config
          echo "region=${{ap-sydney-1}}" >> ~/.oci/config
          echo "tenancy=${{ocid1.tenancy.oc1..aaaaaaaavinzj4bx6mignasay6qjuhdqefeeu73mtfscmzelbjifuqwo6ela}}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/oci_api_key.pem
          echo "${{secrets.OCI_KEY_PUBLIC}}" >> ~/.oci/oci_api_key_public.pem
      - name: 'Install OCI CLI'
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
      - name: 'Fix Config File Permissions'
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/oci_api_key.pem
      - name: 'Deploy Into Object Storage'
        run: |
          oci os object bulk-delete  -bn ${{secrets.os-react}}  --prefix static --force
          oci os object put -bn ${{secrets.os-react}} --file ./build/manifest.json --content-type application/json --force
          oci os object bulk-upload -bn ${{secrets.os-react}} --src-dir ./build --content-type text/html --include *.html --overwrite
          oci os object bulk-upload -bn ${{secrets.os-react}} --src-dir ./build --content-type image/jpeg --include *.jpg --overwrite
          oci os object bulk-upload -bn ${{secrets.os-react}} --src-dir ./build --content-type text/javascript --include *.js --overwrite
          oci os object bulk-upload -bn ${{secrets.os-react}} --src-dir ./build --content-type text/css --include *.css --overwrite
          oci os object bulk-upload -bn ${{secrets.os-react}} --src-dir ./build --content-type text/plain --exclude *.js --exclude *.html --exclude *.jpg --exclude *.css --exclude ./build/manifest.json --overwrite
